#!/bin/bash
function green {
    echo -e "\\033[32;1m${@}\033[0m"
}
function red {
    echo -e "\\033[31;1m${@}\033[0m"
}

function white {
    echo -e "\\033[37;1m${@}\033[0m"
}
 if [ "$1" = "stop" ] 
    then 
        pkill -f BannerBot
		green "Banner Stopped"
    fi

if [ "$1" = "start" ] 
    then 
        screen -dmS BannerBot php core.php -i 1
		green "Banner Started"
    fi
 
 
